"""add autoincrement to question_id

Revision ID: 29719f0a6707
Revises: 12d84328e7e8
Create Date: 2025-11-16 14:54:25.417934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29719f0a6707'
down_revision: Union[str, Sequence[str], None] = '12d84328e7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('question_quiz_id_fkey'), 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'quiz', ['quiz_id'], ['quiz_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(op.f('question_quiz_id_fkey'), 'question', 'quiz', ['quiz_id'], ['quiz_id'])
    # ### end Alembic commands ###
