"""Fix table schema

Revision ID: cace54d97c4b
Revises: f8a0130357c6
Create Date: 2025-11-15 21:31:13.456135

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cace54d97c4b'
down_revision: Union[str, Sequence[str], None] = 'f8a0130357c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_note_id'), table_name='note')
    op.drop_table('note')
    op.alter_column('question', 'question_text',
               existing_type=sa.TEXT(),
               comment='문제',
               existing_nullable=False)
    op.alter_column('question', 'correct_answer',
               existing_type=sa.VARCHAR(length=500),
               comment='정답',
               existing_nullable=False)
    op.alter_column('question', 'user_answer',
               existing_type=sa.VARCHAR(length=500),
               comment='사용자 답변',
               existing_comment='사용자 답변 (제출 시)',
               existing_nullable=True)
    op.alter_column('question', 'is_correct',
               existing_type=sa.BOOLEAN(),
               comment='정답 여부',
               existing_comment='정답 여부 (제출 시)',
               existing_nullable=True)
    op.add_column('quiz', sa.Column('title', sa.String(length=200), nullable=True, comment='사용자가 입력한 제목'))
    op.add_column('quiz', sa.Column('correct_number', sa.Integer(), nullable=True, comment='맞춘 문제 수'))
    op.alter_column('quiz', 'include_short_answer',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='단답형 포함인지',
               existing_comment='단답형 포함 여부')
    op.alter_column('quiz', 'total_questions',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='전체 문제 수')
    op.alter_column('quiz', 'is_saved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='문제를 저장했는 지',
               existing_comment='저장 여부',
               existing_server_default=sa.text('false'))
    op.alter_column('quiz', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='저장 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'id',
               existing_type=sa.VARCHAR(length=100),
               comment='아이디',
               existing_comment='이메일',
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'id',
               existing_type=sa.VARCHAR(length=100),
               comment='이메일',
               existing_comment='아이디',
               existing_nullable=False)
    op.alter_column('quiz', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='저장 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quiz', 'is_saved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='저장 여부',
               existing_comment='문제를 저장했는 지',
               existing_server_default=sa.text('false'))
    op.alter_column('quiz', 'total_questions',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='전체 문제 수')
    op.alter_column('quiz', 'include_short_answer',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='단답형 포함 여부',
               existing_comment='단답형 포함인지')
    op.drop_column('quiz', 'correct_number')
    op.drop_column('quiz', 'title')
    op.alter_column('question', 'is_correct',
               existing_type=sa.BOOLEAN(),
               comment='정답 여부 (제출 시)',
               existing_comment='정답 여부',
               existing_nullable=True)
    op.alter_column('question', 'user_answer',
               existing_type=sa.VARCHAR(length=500),
               comment='사용자 답변 (제출 시)',
               existing_comment='사용자 답변',
               existing_nullable=True)
    op.alter_column('question', 'correct_answer',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='정답',
               existing_nullable=False)
    op.alter_column('question', 'question_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='문제',
               existing_nullable=False)
    op.create_table('note',
    sa.Column('note_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='사용자가 입력한 제목'),
    sa.Column('include_short_answer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='저장 시간'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], name=op.f('note_quiz_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('note_user_id_fkey')),
    sa.PrimaryKeyConstraint('note_id', name=op.f('note_pkey'))
    )
    op.create_index(op.f('ix_note_note_id'), 'note', ['note_id'], unique=False)
    # ### end Alembic commands ###
