"""Initial migration

Revision ID: f8a0130357c6
Revises: 
Create Date: 2025-11-05 20:41:49.317403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a0130357c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False, comment='이메일'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='암호화된 비밀번호'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('quiz',
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('include_short_answer', sa.Boolean(), nullable=False, comment='단답형 포함 여부'),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=True, comment='저장 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index(op.f('ix_quiz_quiz_id'), 'quiz', ['quiz_id'], unique=False)
    op.create_table('note',
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='사용자가 입력한 제목'),
    sa.Column('include_short_answer', sa.Boolean(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='저장 시간'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_note_note_id'), 'note', ['note_id'], unique=False)
    op.create_table('question',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False, comment='문제 번호'),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False, comment='MULTIPLE or SHORT'),
    sa.Column('choices', sa.JSON(), nullable=True, comment='선택지 (객관식만)'),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('user_answer', sa.String(length=500), nullable=True, comment='사용자 답변 (제출 시)'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='정답 여부 (제출 시)'),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_question_question_id'), 'question', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_note_note_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_quiz_quiz_id'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
